# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DirectorySimulator(object):
    def setupUi(self, DirectorySimulator):
        DirectorySimulator.setObjectName("DirectorySimulator")
        DirectorySimulator.setWindowModality(QtCore.Qt.ApplicationModal)
        DirectorySimulator.resize(802, 517)
        DirectorySimulator.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ViewTreeA = QtWidgets.QListWidget(DirectorySimulator)
        self.ViewTreeA.setGeometry(QtCore.QRect(20, 20, 311, 391))
        self.ViewTreeA.setStyleSheet("")
        self.ViewTreeA.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ViewTreeA.setObjectName("ViewTreeA")
        self.ViewTreeB = QtWidgets.QListWidget(DirectorySimulator)
        self.ViewTreeB.setGeometry(QtCore.QRect(470, 20, 311, 391))
        self.ViewTreeB.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ViewTreeB.setObjectName("ViewTreeB")
        self.AddFolderA = QtWidgets.QPushButton(DirectorySimulator)
        self.AddFolderA.setGeometry(QtCore.QRect(20, 430, 91, 71))
        self.AddFolderA.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("svg/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddFolderA.setIcon(icon)
        self.AddFolderA.setIconSize(QtCore.QSize(69, 69))
        self.AddFolderA.setFlat(True)
        self.AddFolderA.setObjectName("AddFolderA")
        self.AddFileA = QtWidgets.QPushButton(DirectorySimulator)
        self.AddFileA.setGeometry(QtCore.QRect(140, 430, 81, 71))
        self.AddFileA.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("svg/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddFileA.setIcon(icon1)
        self.AddFileA.setIconSize(QtCore.QSize(69, 65))
        self.AddFileA.setFlat(True)
        self.AddFileA.setObjectName("AddFileA")
        self.DeletA = QtWidgets.QPushButton(DirectorySimulator)
        self.DeletA.setGeometry(QtCore.QRect(250, 430, 81, 71))
        self.DeletA.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("svg/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeletA.setIcon(icon2)
        self.DeletA.setIconSize(QtCore.QSize(69, 65))
        self.DeletA.setFlat(True)
        self.DeletA.setObjectName("DeletA")
        self.AddFolderB = QtWidgets.QPushButton(DirectorySimulator)
        self.AddFolderB.setGeometry(QtCore.QRect(470, 430, 91, 71))
        self.AddFolderB.setText("")
        self.AddFolderB.setIcon(icon)
        self.AddFolderB.setIconSize(QtCore.QSize(69, 69))
        self.AddFolderB.setFlat(True)
        self.AddFolderB.setObjectName("AddFolderB")
        self.AddFileB = QtWidgets.QPushButton(DirectorySimulator)
        self.AddFileB.setGeometry(QtCore.QRect(600, 430, 81, 71))
        self.AddFileB.setText("")
        self.AddFileB.setIcon(icon1)
        self.AddFileB.setIconSize(QtCore.QSize(69, 65))
        self.AddFileB.setFlat(True)
        self.AddFileB.setObjectName("AddFileB")
        self.DeletB = QtWidgets.QPushButton(DirectorySimulator)
        self.DeletB.setGeometry(QtCore.QRect(700, 430, 81, 71))
        self.DeletB.setText("")
        self.DeletB.setIcon(icon2)
        self.DeletB.setIconSize(QtCore.QSize(69, 65))
        self.DeletB.setFlat(True)
        self.DeletB.setObjectName("DeletB")
        self.CopytoB = QtWidgets.QPushButton(DirectorySimulator)
        self.CopytoB.setGeometry(QtCore.QRect(370, 150, 71, 81))
        self.CopytoB.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("svg/left2right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CopytoB.setIcon(icon3)
        self.CopytoB.setIconSize(QtCore.QSize(69, 69))
        self.CopytoB.setFlat(True)
        self.CopytoB.setObjectName("CopytoB")
        self.CopyToA = QtWidgets.QPushButton(DirectorySimulator)
        self.CopyToA.setGeometry(QtCore.QRect(360, 230, 81, 61))
        self.CopyToA.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("svg/right2left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CopyToA.setIcon(icon4)
        self.CopyToA.setIconSize(QtCore.QSize(69, 69))
        self.CopyToA.setDefault(False)
        self.CopyToA.setFlat(True)
        self.CopyToA.setObjectName("CopyToA")
        self.close = QtWidgets.QPushButton(DirectorySimulator)
        self.close.setGeometry(QtCore.QRect(390, 20, 21, 21))
        self.close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("svg/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon5)
        self.close.setFlat(True)
        self.close.setObjectName("close")

        self.retranslateUi(DirectorySimulator)
        QtCore.QMetaObject.connectSlotsByName(DirectorySimulator)

    def retranslateUi(self, DirectorySimulator):
        _translate = QtCore.QCoreApplication.translate
        DirectorySimulator.setWindowTitle(_translate("DirectorySimulator", "Dialog"))
import icons_rc
