# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(726, 513)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ViewTreeA = QtWidgets.QListWidget(Dialog)
        self.ViewTreeA.setGeometry(QtCore.QRect(20, 20, 311, 391))
        self.ViewTreeA.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.ViewTreeA.setObjectName("ViewTreeA")
        item = QtWidgets.QListWidgetItem()
        self.ViewTreeA.addItem(item)
        self.ViewTreeB = QtWidgets.QListWidget(Dialog)
        self.ViewTreeB.setGeometry(QtCore.QRect(400, 30, 311, 391))
        self.ViewTreeB.setObjectName("ViewTreeB")
        item = QtWidgets.QListWidgetItem()
        self.ViewTreeB.addItem(item)
        self.AddFolderA = QtWidgets.QPushButton(Dialog)
        self.AddFolderA.setGeometry(QtCore.QRect(20, 430, 91, 71))
        self.AddFolderA.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svgs/svg/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddFolderA.setIcon(icon)
        self.AddFolderA.setIconSize(QtCore.QSize(69, 69))
        self.AddFolderA.setFlat(True)
        self.AddFolderA.setObjectName("AddFolderA")
        self.AddFileA = QtWidgets.QPushButton(Dialog)
        self.AddFileA.setGeometry(QtCore.QRect(140, 430, 81, 71))
        self.AddFileA.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/svgs/svg/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddFileA.setIcon(icon1)
        self.AddFileA.setIconSize(QtCore.QSize(69, 65))
        self.AddFileA.setFlat(True)
        self.AddFileA.setObjectName("AddFileA")
        self.DeletA = QtWidgets.QPushButton(Dialog)
        self.DeletA.setGeometry(QtCore.QRect(250, 430, 81, 71))
        self.DeletA.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/svgs/svg/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeletA.setIcon(icon2)
        self.DeletA.setIconSize(QtCore.QSize(69, 65))
        self.DeletA.setFlat(True)
        self.DeletA.setObjectName("DeletA")
        self.AddFolderB = QtWidgets.QPushButton(Dialog)
        self.AddFolderB.setGeometry(QtCore.QRect(400, 430, 91, 71))
        self.AddFolderB.setText("")
        self.AddFolderB.setIcon(icon)
        self.AddFolderB.setIconSize(QtCore.QSize(69, 69))
        self.AddFolderB.setFlat(True)
        self.AddFolderB.setObjectName("AddFolderB")
        self.AddFileB = QtWidgets.QPushButton(Dialog)
        self.AddFileB.setGeometry(QtCore.QRect(520, 430, 81, 71))
        self.AddFileB.setText("")
        self.AddFileB.setIcon(icon1)
        self.AddFileB.setIconSize(QtCore.QSize(69, 65))
        self.AddFileB.setFlat(True)
        self.AddFileB.setObjectName("AddFileB")
        self.DeletB = QtWidgets.QPushButton(Dialog)
        self.DeletB.setGeometry(QtCore.QRect(630, 430, 81, 71))
        self.DeletB.setText("")
        self.DeletB.setIcon(icon2)
        self.DeletB.setIconSize(QtCore.QSize(69, 65))
        self.DeletB.setFlat(True)
        self.DeletB.setObjectName("DeletB")
        self.CopytoB = QtWidgets.QPushButton(Dialog)
        self.CopytoB.setGeometry(QtCore.QRect(340, 160, 51, 51))
        self.CopytoB.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/svgs/svg/left2right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CopytoB.setIcon(icon3)
        self.CopytoB.setIconSize(QtCore.QSize(69, 35))
        self.CopytoB.setFlat(True)
        self.CopytoB.setObjectName("CopytoB")
        self.CopyToA = QtWidgets.QPushButton(Dialog)
        self.CopyToA.setGeometry(QtCore.QRect(340, 230, 51, 51))
        self.CopyToA.setText("")
        self.CopyToA.setIcon(icon3)
        self.CopyToA.setIconSize(QtCore.QSize(69, 35))
        self.CopyToA.setDefault(False)
        self.CopyToA.setFlat(True)
        self.CopyToA.setObjectName("CopyToA")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.ViewTreeA.isSortingEnabled()
        self.ViewTreeA.setSortingEnabled(False)
        item = self.ViewTreeA.item(0)
        item.setText(_translate("Dialog", "Pene"))
        self.ViewTreeA.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.ViewTreeB.isSortingEnabled()
        self.ViewTreeB.setSortingEnabled(False)
        item = self.ViewTreeB.item(0)
        item.setText(_translate("Dialog", "Pene pero en arbol b"))
        self.ViewTreeB.setSortingEnabled(__sortingEnabled)
import icons_rc
